export const ABOUT = [
    "Hello there! Thank you for visiting my personal website. I'm Ahmad Rayhan, An Information Systems student at Universitas Airlangga with over 4 years of experience in the field of technology and information systems. I have consistently demonstrated commitment and dedication in achieving accomplishments while developing competencies in information technology, entrepreneurship, and leadership.",

    "Academic experience includes working as a freelancer on various website development projects for academic research purposes—both for lecturers and students—as well as for business owners. These projects have ranged from frontend tasks such as building landing pages and company profiles, to full-stack development including learning platforms, dashboards, and service-based sales systems. One of the major milestones in my academic and professional journey was my involvement in the development of MIKA Education, an autism education platform, where I served as a project assistant and lead developer. The platform was successfully funded by the Australian Direct Aid Program through the Australian Consulate-General in 2023. Additionally, I actively contribute as an international researcher at the East Java Autism Care Forum, combining technology, research, and direct social impact.",

    "My interest in business development and management has led to the establishment of two legally registered businesses. The first is Entative Hub, a digital agency platform based on the gig economy model that connects student freelancers with digital service requests from business owners. The second is Roxoon Apparel, a clothing and merchandise business developed since 2023 using an outsourcing system and third-party production vendors, which has generated an annual revenue of up to IDR 100 million. Alongside the development of both businesses, my skills in digital marketing and graphic design have also grown—particularly in crafting business strategies, concepts, and visual identities such as logos/brandmarks, media content, infographics, and visual company profiles. These achievements are further supported by my selection as an awardee of the Airlangga Youth Entrepreneurship (AYE) 2024 program by the Directorate of Career Development, Entrepreneurship Incubation, and Alumni at Universitas Airlangga.",
    
    "A balance of experience and leadership is demonstrated through various strategic roles in student organizations—from team leader during freshman orientation, field coordinator in community service programs, head of department-level benchmarking events, chief executive of a faculty-level village development program, to core management staff in the Student Executive Board (BEM) at the faculty level. In addition, I have earned both national and international recognitions, including a Silver Medal in the 2023 LIP3D program (Village Innovation Development Competition) for a green economy-based village digitalization initiative, selected as an awardee in the MSIB Batch 6 program as a Full-Stack Web Developer by the Ministry of Education and Culture in 2024, Best Presenter at ICAPH 2024—an international conference on inclusive product development, and selected participant in the International Student Mobility Program to Universiti Kebangsaan Malaysia (UKM) in 2024. Most notably, I was honored with a Silver Medal at the IPITEx 2024—the International Intellectual Property, Invention, Innovation and Technology Exhibition in Bangkok, hosted by Thailand’s National Research Council (NRCT).",

    "With a combination of technical expertise, managerial capabilities, leadership qualities, and a strong passion for learning, I am fully prepared to contribute meaningfully to the professional world."
]
